version: '3.8'
services:
  app:
    build: .
    ports:
      - "1234:8501"  # Streamlit UI
      - "8000:8000"  # FastAPI backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DOCKER_ENV=true
    networks:
      - app_network

networks:
  app_network:
    driver: bridge